# Array creation routines

## Ones and zeros

In [ ]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [2]:
a = np.empty([2,2])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [ ]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
i = np.array(x)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
a = np.eye(3)

Create a new array of 3*2 float numbers, filled with ones.

In [ ]:
b = np.ones([3,2])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
c = np.ones(shape=x.shape,dtype=x.dtype)

Create a new array of 3*2 float numbers, filled with zeros.

In [ ]:
d = np.zeros([3,2])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
e = np.zeros(shape = x.shape, dtype = x.dtype)

Create a new array of 2*5 uints, filled with 6.

In [3]:
f = np.full([2,5],6)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
g = np.full_like(x,6)

## From existing data

Create an array of [1, 2, 3].

In [ ]:
h = np.arange(1,4)

Let x = [1, 2]. Conver it into an array of `float`.

In [ ]:
x = [1, 2]
x = np.array(x, dtype=float)

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [ ]:
x = np.array([1, 2, 3])
y = np.array(x)

## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [6]:
h = np.arange(2,102,2)
print(h)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [ ]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
k = X[[0,1,2],[0,1,2]]

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [ ]:
m = np.zeros([4,4], dtype = np.int64)
l[[0,1,2,3],[0,1,2,3]]=np.arange(1,5)

Write a NumPy program to create a 2d array with 1 on the border and 0 inside

Expected Output:
Original array:    <br>
[[ 1. 1. 1. 1. 1.]  <br>
[ 1. 1. 1. 1. 1.]   <br>
[ 1. 1. 1. 1. 1.]   <br>
[ 1. 1. 1. 1. 1.]   <br>
[ 1. 1. 1. 1. 1.]]  <br>
1 on the border and 0 inside in the array <br>
[[ 1. 1. 1. 1. 1.]  <br>
[ 1. 0. 0. 0. 1.]   <br>
[ 1. 0. 0. 0. 1.]   <br>
[ 1. 0. 0. 0. 1.]   <br>
[ 1. 1. 1. 1. 1.]]  <br>


In [14]:
import numpy as np
m = np.ones([5,5])
for row in range(5):
    for col in range(5):
        if not (row==0 or row==4 or col==0 or col==4):
            m[row,col]=0
print(m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Challenge
- Create examples of broadcasting with NumPy arrays.
- Implement your own broadcasting function for manually broadcasting in one and two-dimensional cases.
- Benchmark NumPy broadcasting and your own custom broadcasting functions with one and two dimensional cases with very large arrays.

In [33]:
import numpy as np
import time
t = time.time()
a = np.random.rand(100,100000)
b = np.random.rand(100000)
print("Auto Broadcasting:\n",a*b,"\ntime:",str(time.time()-t),"s")
t = time.time()
b = np.tile(b,(100,1))
print("Manuel Broadcasting:\n",a*b,"\ntime:",str(time.time()-t),"s")

Auto Broadcasting:
 [[0.57574573 0.19049277 0.1979602  ... 0.05924607 0.08255235 0.14957327]
 [0.13126052 0.03964124 0.13734633 ... 0.09775332 0.21530115 0.15294817]
 [0.60635949 0.08796613 0.08227255 ... 0.11739555 0.36355933 0.14948753]
 ...
 [0.14922689 0.03789675 0.18896607 ... 0.11625676 0.20035609 0.16814849]
 [0.19743018 0.05070308 0.21573423 ... 0.05333952 0.20686393 0.10991064]
 [0.60847295 0.13200825 0.00937729 ... 0.1298118  0.17013133 0.11128537]] 
time: 0.2553389072418213 s
Manuel Broadcasting:
 [[0.57574573 0.19049277 0.1979602  ... 0.05924607 0.08255235 0.14957327]
 [0.13126052 0.03964124 0.13734633 ... 0.09775332 0.21530115 0.15294817]
 [0.60635949 0.08796613 0.08227255 ... 0.11739555 0.36355933 0.14948753]
 ...
 [0.14922689 0.03789675 0.18896607 ... 0.11625676 0.20035609 0.16814849]
 [0.19743018 0.05070308 0.21573423 ... 0.05333952 0.20686393 0.10991064]
 [0.60847295 0.13200825 0.00937729 ... 0.1298118  0.17013133 0.11128537]] 
time: 0.08999919891357422 s
