# Array creation routines

## Ones and zeros

In [ ]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [2]:
a = np.empty([2,2])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [ ]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
i = np.array(x)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
a = np.eye(3)

Create a new array of 3*2 float numbers, filled with ones.

In [ ]:
b = np.ones([3,2])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
c = np.ones(shape=x.shape,dtype=x.dtype)

Create a new array of 3*2 float numbers, filled with zeros.

In [ ]:
d = np.zeros([3,2])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
e = np.zeros(shape = x.shape, dtype = x.dtype)

Create a new array of 2*5 uints, filled with 6.

In [3]:
f = np.full([2,5],6)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
g = np.full_like(x,6)

## From existing data

Create an array of [1, 2, 3].

In [ ]:
h = np.arange(1,4)

Let x = [1, 2]. Conver it into an array of `float`.

In [ ]:
x = [1, 2]
x = np.array(x, dtype=float)

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [ ]:
x = np.array([1, 2, 3])
y = np.array(x)

## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [6]:
h = np.arange(2,102,2)
print(h)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [ ]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
k = X[[0,1,2],[0,1,2]]

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [ ]:
m = np.zeros([4,4], dtype = np.int64)
l[[0,1,2,3],[0,1,2,3]]=np.arange(1,5)

Write a NumPy program to create a 2d array with 1 on the border and 0 inside

Expected Output:
Original array:    <br>
[[ 1. 1. 1. 1. 1.]  <br>
[ 1. 1. 1. 1. 1.]   <br>
[ 1. 1. 1. 1. 1.]   <br>
[ 1. 1. 1. 1. 1.]   <br>
[ 1. 1. 1. 1. 1.]]  <br>
1 on the border and 0 inside in the array <br>
[[ 1. 1. 1. 1. 1.]  <br>
[ 1. 0. 0. 0. 1.]   <br>
[ 1. 0. 0. 0. 1.]   <br>
[ 1. 0. 0. 0. 1.]   <br>
[ 1. 1. 1. 1. 1.]]  <br>


In [14]:
import numpy as np
m = np.ones([5,5])
for row in range(5):
    for col in range(5):
        if not (row==0 or row==4 or col==0 or col==4):
            m[row,col]=0
print(m)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Challenge
- Create examples of broadcasting with NumPy arrays.
- Implement your own broadcasting function for manually broadcasting in one and two-dimensional cases.
- Benchmark NumPy broadcasting and your own custom broadcasting functions with one and two dimensional cases with very large arrays.

In [1]:
import numpy as np
import time
t = time.time()
a = np.random.rand(100,100000)
b = np.random.rand(100000)
print("Auto Broadcasting:\n",a*b,"\ntime:",str(time.time()-t),"s")
t = time.time()
b = np.tile(b,(100,1))
print("\nManuel Broadcasting:\n",a*b,"\ntime:",str(time.time()-t),"s")

Auto Broadcasting:
 [[0.22558109 0.00111696 0.0870916  ... 0.04712929 0.12434762 0.11332711]
 [0.47300141 0.01968458 0.21676308 ... 0.06099444 0.31369608 0.04895691]
 [0.37654171 0.02118692 0.08936398 ... 0.02017034 0.26107479 0.04664379]
 ...
 [0.04760719 0.00708608 0.14107296 ... 0.07009474 0.00499497 0.03086985]
 [0.1459091  0.01659068 0.15923544 ... 0.01799775 0.35669111 0.19428825]
 [0.01010421 0.01479312 0.10926204 ... 0.04093926 0.38808349 0.02558093]] 
time: 0.26036810874938965 s

Manuel Broadcasting:
 [[0.22558109 0.00111696 0.0870916  ... 0.04712929 0.12434762 0.11332711]
 [0.47300141 0.01968458 0.21676308 ... 0.06099444 0.31369608 0.04895691]
 [0.37654171 0.02118692 0.08936398 ... 0.02017034 0.26107479 0.04664379]
 ...
 [0.04760719 0.00708608 0.14107296 ... 0.07009474 0.00499497 0.03086985]
 [0.1459091  0.01659068 0.15923544 ... 0.01799775 0.35669111 0.19428825]
 [0.01010421 0.01479312 0.10926204 ... 0.04093926 0.38808349 0.02558093]] 
time: 0.07772088050842285 s
